spring:
  application:
    name: authuser
  profiles:
    active: h2
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
    okhttp:
      enabled: true
  logging:
    level:
      com.example.feignclientdemo.client: DEBUG
server:
  port: 8080



